[package]
name = "rust-twitter-cli"
version = "0.1.0"
authors = ["Cesar D. Velandia <cesar@velandia.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
